Project work
OscarFMdev/TechConference pull request #1
Opened 2022-09-15 05:22 UTC by OscarFMdev

## PR description

In this branch I:
- Created a mobile version of the webpage.
- Created a desktop version of the webpage.
- Configurated JavaScript file to monitor user interaction and create speaker cards dynamically.
- Fixed linter errors.

#### Thank you for reviewing my code! 🙌

2022-09-15 06:10 UTC, Bondok6 requested changes
## Hi @OscarFMdev 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## To Highlight 
- Great job using semantic tags ✅
- No linter errors ✅
- Your repo is professional ✅
- Your project is professional ✅

## Suggested changes
- [ ] According to the requirements, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

![image](https://user-images.githubusercontent.com/45231276/181190349-2026da67-36fe-4bbe-811b-e2efd8c98b32.png)

- [ ] The Link of the MIT file in your README file is broken, Kindly fix it by changing the path to `This project is [MIT](./MIT.md) licensed.` instead of `This project is [MIT](./LICENSE) licensed.`  or you can rename your `MIT.md` to `LICENSE` 💯

- [ ] _Check the comments under the review._ ⬇

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-15 06:10 UTC, Bondok6 commented on about.html
> +    </footer>
- [ ] According to the original design The footer should contain a logo aligned to the left and text aligned to the right, Kindly update it 👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/190323649-4249dae2-af20-4db5-ba20-e2ae2c3ef6bc.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/190323658-30d5339f-7595-4a23-b0f0-992295b6e204.PNG" width="500" /> |

- [ ] [ in the mobile version/size ] you should change the background color to white  and I suggest adding the `partners section` above the footer section to follow the original design 💯👌

> Original Design
![image](https://user-images.githubusercontent.com/45231276/183271764-30beb599-9ac0-4971-a44a-8ab10329a0c8.png)

2022-09-15 06:10 UTC, Bondok6 commented on index.html
> +    </div>
- [ ] I think you forgot to add the partners section, kindly add it 👌
- [ ] According to the original design The footer should contain a logo aligned to the left and text aligned to the right, Kindly update it 👌
- [ ] Footer section on the home page: It should have a white background. 💯

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/190324904-22cfe9be-d9b7-49ea-99d7-65733b98bd49.png" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/183271455-b6d80e6b-3533-47a2-9535-bc13dccc6bb9.png" width="500" /> |

2022-09-15 06:10 UTC, Bondok6 commented on index.html
> +      </section>
- [ ] Great job here 💯but you I think you forgot to add the button, kindly add it to look similar to the original desig👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/190325486-01ff913c-2b7f-4ada-ae04-7356cb893778.png" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/190325994-2185668c-dbb8-4d39-834f-e69c7c251f94.png" width="500" /> |

- NOTE: this button on the mobile version/size should look like this ⬇

![image](https://user-images.githubusercontent.com/45231276/190326179-3ac867ac-e4fd-43c8-8973-9d348d21e848.png)

2022-09-16 21:43 UTC, tufoinnkuo10 requested changes
Hi @OscarFMdev 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ followed the design
✅ Menu ok

Required Changes ♻️
Check the comments under the review
Optional suggestions
- [optional] please add a good brief description in your readme on what your project is all about.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-16 21:43 UTC, tufoinnkuo10 commented on src/scss/layout/_mobile-menu.scss
> +.mobile-menu {
- [optional] please ensure that when the mobile popup comes up it should not be possible to scroll through your site. great job

2022-09-16 21:43 UTC, tufoinnkuo10 commented on index.html
> +          <button class="program-button"><a class="program-link" href="#">See the whole program</a></button>
- [ ] please add the `see the whole program` link on the desktop version
- [ ] kindly use the same color and design for the `see the whole program` button on the mobile version

your version
![Screenshot (455)_LI](https://user-images.githubusercontent.com/65298048/190790932-b2ee3f63-3a7d-4ffc-b388-5f53500c0986.jpg)
original version
![Screenshot (454)](https://user-images.githubusercontent.com/65298048/190791423-6323f515-d8d4-4375-bfb2-12b9e23f6ce6.png)

2022-09-16 22:25 UTC, OscarFMdev commented
Thank you @Bondok6 for your feedback! it was complete and clear.

2022-09-16 23:12 UTC, Kossi-stack reviewed
## Status: Approved ✔️

**Hi @OscarFMdev,*

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-16 23:13 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @OscarFMdev,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-17 04:42 UTC, merged